seed: 0
exp_name: discogan #where to save the results on "results"
exp_name_excel: discogan #file's name

device:
  cuda_device: cuda
  gpu_num_workers: 4

data:
  cv: 5
  fold_dir: ./data/k_fold_cross_validation/folds_2d/folds_2d_AB #dataset
  img_dim: 256
  model_dir: ./models
  report_dir: ./results
  batch_size: 128

model:
  model_name: discogan
  pretrained_model: discogan

trainer:
  optimizer:
    lr: 0.00001
  early_stopping: 50
  warm_up: 50
  max_epochs: 300
  LAMBDA_IDENTITY: 5
  LAMBDA_CYCLE: 10
  CHECKPOINT_GEN_AB: "genAB.pth.tar"
  CHECKPOINT_GEN_BA: "genBA.pth.tar"
  CHECKPOINT_DISC_A: "criticA.pth.tar"
  CHECKPOINT_DISC_B: "criticB.pth.tar"

output:
  save_img_output: True
