seed: 0
exp_name: stargan #where to save the results on "results"
exp_name_excel: stargan #files's name

device:
  cuda_device: cuda
  gpu_num_workers: 4

data:
  cv: 5

  fold_dir: ./data/k_fold_cross_validation/folds_2d/folds_2d_AB #dataset
  img_dim: 256
  model_dir: ./models
  report_dir: ./results
  batch_size: 64

model:
  model_name: stargan
  pretrained_model: stargan
  residual_blocks: 6
  n_strided: 6
  SAVE_MODEL: True
  c_dim: 2

trainer:
  optimizer:
    lr: 0.0002
  early_stopping: 50
  warm_up: 50
  max_epochs: 300
  lambda_cls: 1
  lambda_rec: 10
  lambda_gp: 10
  n_critic: 5
  CHECKPOINT_G: "G_stargan.pth.tar"
  CHECKPOINT_D: "D_stargan.pth.tar"

output:
  save_img_output: True
